import React, { useState } from 'react';
import { FileText, Copy, Check, Download, Clapperboard } from 'lucide-react';
import { MovieScript } from '../types';

interface ScriptViewerProps {
  movie: MovieScript;
}

export const ScriptViewer: React.FC<ScriptViewerProps> = ({ movie }) => {
  const [copied, setCopied] = useState(false);

  const handleCopyScript = () => {
    let scriptText = `TITLE: ${movie.title}\n`;
    scriptText += `TAGLINE: ${movie.tagline}\n`;
    scriptText += `LANGUAGE: ${movie.language}\n`;
    scriptText += `GENRE: ${movie.genre}\n`;
    scriptText += `SYNOPSIS: ${movie.synopsis}\n\n`;

    movie.scenes.forEach((scene) => {
      scriptText += `SCENE ${scene.sceneNumber}: ${scene.timeOfDayAndLocation}\n`;
      scriptText += `VISUAL: ${scene.visualPrompt}\n`;
      scriptText += `CAMERA: ${scene.cameraMotion}\n`;
      scriptText += `${scene.speakerVoice.toUpperCase()}: ${scene.narrationScript}\n`;
      scriptText += `[ENGLISH SUB]: ${scene.englishTranslation}\n`;
      scriptText += `SFX: ${scene.soundEffects}\n\n`;
    });

    navigator.clipboard.writeText(scriptText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div id="script-viewer-section" className="w-full max-w-5xl mx-auto px-4 py-6">
      <div className="bg-neutral-900 border border-neutral-800 rounded-2xl p-6 shadow-xl">
        {/* Header */}
        <div className="flex flex-wrap items-center justify-between gap-4 pb-4 border-b border-neutral-800">
          <div className="flex items-center gap-2">
            <FileText className="w-5 h-5 text-amber-400" />
            <h3 className="text-base font-bold text-white font-serif">
              Director's Screenplay Script
            </h3>
            <span className="text-xs bg-amber-500/10 text-amber-400 border border-amber-500/20 px-2 py-0.5 rounded-full font-mono">
              {movie.language}
            </span>
          </div>

          <button
            onClick={handleCopyScript}
            className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-neutral-800 hover:bg-neutral-700 text-neutral-200 text-xs font-medium transition-colors"
          >
            {copied ? (
              <>
                <Check className="w-3.5 h-3.5 text-emerald-400" />
                <span className="text-emerald-400">Copied!</span>
              </>
            ) : (
              <>
                <Copy className="w-3.5 h-3.5 text-neutral-400" />
                <span>Copy Screenplay</span>
              </>
            )}
          </button>
        </div>

        {/* Screenplay Content Body */}
        <div className="mt-6 font-mono text-xs sm:text-sm text-neutral-300 space-y-6 bg-neutral-950 p-6 rounded-xl border border-neutral-800/80 max-h-[500px] overflow-y-auto">
          {/* Title Card */}
          <div className="text-center py-4 border-b border-neutral-800 space-y-1">
            <h1 className="text-xl font-bold text-white tracking-widest">{movie.title.toUpperCase()}</h1>
            <p className="text-amber-400 italic">"{movie.tagline}"</p>
            <p className="text-neutral-500 text-[11px] pt-2">Original Screenplay Generated by CineAI Engine</p>
          </div>

          {/* Scenes */}
          {movie.scenes.map((scene) => (
            <div key={scene.sceneNumber} className="space-y-2 border-b border-neutral-900 pb-4">
              <div className="text-amber-400 font-bold uppercase tracking-wider">
                SCENE {scene.sceneNumber}: {scene.timeOfDayAndLocation}
              </div>

              <div className="text-neutral-400 pl-4 border-l-2 border-neutral-800 space-y-1">
                <div>
                  <span className="text-neutral-500 font-semibold">[VISUAL PROMPT]: </span>
                  {scene.visualPrompt}
                </div>
                <div>
                  <span className="text-neutral-500 font-semibold">[CAMERA]: </span>
                  {scene.cameraMotion}
                </div>
                <div>
                  <span className="text-neutral-500 font-semibold">[SOUND FX]: </span>
                  {scene.soundEffects}
                </div>
              </div>

              {/* Dialogue */}
              <div className="pt-2 text-center max-w-lg mx-auto">
                <span className="font-bold text-rose-400 block tracking-wider uppercase">
                  {scene.speakerVoice || 'NARRATOR'}
                </span>
                <p className="text-white text-sm sm:text-base font-sans font-medium py-1">
                  "{scene.narrationScript}"
                </p>
                {movie.language !== 'English' && (
                  <p className="text-neutral-400 text-xs italic font-sans">
                    ({scene.englishTranslation})
                  </p>
                )}
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
};
